require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Metrics/LineLength:
  Max: 117

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

RSpec/MultipleExpectations:
  Max: 5
