inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

RSpec/MultipleExpectations:
  Max: 5

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
