require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Layout/LineLength:
  Max: 117

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

RSpec/MultipleExpectations:
  Max: 5

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
