require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
